### ISSUE TITLE
[FEATURE] Nextgen UI progress roadmap

### ISSUE THREAD

**Issue by 1zun4secondary** [CCBlueX/LiquidBounce#1025]
### Concepts
Our Nextgen concepts. All important ones are done and follow the same design guidelines.

- [x] Main Menu
- [x] Singleplayer
- [x] Multiplayer
- [x] Alt Manager
- [x] Proxy Manager (https://github.com/CCBlueX/LiquidBounce/issues/391)
- [x] LiquidProxy GUI
- [x] ClickGUI
- [x] ClickGUI search bar (https://github.com/CCBlueX/LiquidBounce/issues/800)
- [x] HUD
- [x] HUD Editor
- [ ] Marketplace (Configs, Scripts, Mods, Themes, https://github.com/CCBlueX/LiquidBounce/issues/1024)

#### Concept Images
<details>
<summary><strong>Title</strong></summary>

<br>

<img width="1920" height="1080" alt="Title concept 1" src="https://github.com/user-attachments/assets/c638f9ac-e0df-4141-841a-f287c542a82c" />
<img width="1920" height="1080" alt="Title concept 2" src="https://github.com/user-attachments/assets/7539c2d3-8c21-4855-9dac-b5f96f1b4baf" />

</details>

<details>
<summary><strong>Singleplayer</strong></summary>

<br>

<img width="1920" height="1080" alt="Singleplayer concept" src="https://github.com/user-attachments/assets/6fc7fb3d-8a79-44f4-96db-607f4fc43582" />

</details>

<details>
<summary><strong>Proxy Manager &amp; LiquidProxy</strong></summary>

<br>

<img width="1920" height="1080" alt="Proxy Manager concept" src="https://github.com/user-attachments/assets/869b66c1-f39c-4ebe-ab1b-b6794277ea34" />
<img width="1838" height="1028" alt="LiquidProxy GUI concept" src="https://github.com/user-attachments/assets/8e0cfd11-f9d8-4ef1-81ab-ea975a77c1c6" />

</details>

<details>
<summary><strong>ClickGUI</strong></summary>

<br>

<img width="1920" height="1080" alt="ClickGUI concept" src="https://github.com/user-attachments/assets/775d65f3-b3af-43ad-ae02-85d638014e96" />

</details>

<details>
<summary><strong>HUD</strong></summary>

<br>

<img width="1920" height="1080" alt="HUD concept" src="https://github.com/user-attachments/assets/376b0616-71eb-4538-944f-49108ead43d0" />

</details>

### Implementation

- [x] Main Menu
- [x] Singleplayer
- [x] Multiplayer
- [x] Alt Manager
- [x] Proxy Manager (https://github.com/CCBlueX/LiquidBounce/issues/391)
- [x] ClickGUI (Basics + Values)
- [x] ClickGUI search bar (https://github.com/CCBlueX/LiquidBounce/issues/800)
- [x] HUD (Basics)
- [x] HUD (Elements)
- [ ] LiquidProxy GUI
- [x] HUD
- [x] HUD Editor
- [ ] Marketplace

### Browser Backends
- [ ] Ultralight (https://github.com/CCBlueX/LiquidBounce/pull/1178)
- [x] MCEF (https://github.com/CCBlueX/LiquidBounce/pull/1557)

**Comment by 1zun4** [comment]
Today we are going to release our design concepts, so feel free to take it up to implementation. :)

**Comment by 1zun4** [comment]
The most basic functions were implemented in 1.0.0 and all of the rest can follow in future releases.

**Comment by 1zun4** [comment]
I have now updated the roadmap.
https://github.com/CCBlueX/LiquidBounce/commit/c4c7a903fa33379e46f30c2c16233db5d5a89de5

**Comment by ghost** [comment]
Clickgui configs? Please explain

**Comment by gaoyu06** [comment]
Hi, I have experience on Vue.js, react and know JavaScript well. I'm willing to help you complete the progress of implementing design of guis. How can I get to know your division of work and take part in? BTW I also knows some designing(like using Figma), maybe I  can also help in designing.
I can work every weekend and the whole summer vacation.

**Comment by 1zun4** [comment]
> Hi, I have experience on Vue.js, react and know JavaScript well. I'm willing to help you complete the progress of implementing design of guis. How can I get to know your division of work and take part in? BTW I also knows some designing(like using Figma), maybe I can also help in designing. I can work every weekend and the whole summer vacation.

Hi, that is great, however our current implementation is written in Svelte and stay in that language. There was once a React implementation that was never finished due to lack of developers. Recently @SenkJu got very far with the progress and completed all available design concepts.

Therefore, we do not need any development help at the moment and are waiting for our designer to create more design concepts for needed GUIs and elements.

**Comment by gaoyu06** [comment]
> > Hi, I have experience on Vue.js, react and know JavaScript well. I'm willing to help you complete the progress of implementing design of guis. How can I get to know your division of work and take part in? BTW I also knows some designing(like using Figma), maybe I can also help in designing. I can work every weekend and the whole summer vacation.
> 
> Hi, that is great, however our current implementation is written in Svelte and stay in that language. There was once a React implementation that was never finished due to lack of developers. Recently @SenkJu got very far with the progress and completed all available design concepts.
> 
> Therefore, we do not need any development help at the moment and are waiting for our designer to create more design concepts for needed GUIs and elements.

Thanks for replying! I am willing and able to learn relevant skills since I have experience on other front-end languages. I'll learn Svelte and try making improvements and optimization PRs in the future. I'll ask you again when I think I learned enough.
Besides, I will try to make some designs, you can decide whether let me take part in designing🙏

**Comment by liquidsquid1** [comment]
> Clickgui configs? Please explain

As in a tab on the clickgui where you can browse configs

**Comment by LousyBook-01** [comment]
ok, know some html and css, i can probably learn svelte, but i'm not that experienced, but i think i can help in creating the ui, i'm still in middle school but i know to code, i can probably help a little bit

**Comment by funnydlol** [comment]
Will there be an element to show server information or atleast something to show some stats? (ip, ping, tps, player pos, etc.)

**Comment by 1zun4** [comment]
> Will there be an element to show server information or atleast something to show some stats? (ip, ping, tps, player pos, etc.)

Yes of course. A few of these information such as player position can already be displayed using a text component.

**Comment by funnydlol** [comment]
> Yes of course. A few of these information such as player position can already be displayed using a text component.

I never can get the text component to display player information. In what format does the information need to be to actually display stuff?

**Comment by 1zun4** [comment]
LiquidProxy GUI concept:

<img width="1838" height="1028" alt="Image" src="https://github.com/user-attachments/assets/017e4524-35f0-4eae-863b-f041e87dcd08" />

**Comment by SenkJu** [comment]
Keep

**Comment by minecrrrr** [comment]
Hello everyone!

I just checked out the Nextgen UI roadmap and noticed that the HUD Editor is still on the to-do list. 

I actually have a semi-complete, fully modular HUD Editor that I built for my own project. It already manages essential elements. Right now, the UI is designed specifically for my custom client, but I can easily adapt the style and code to fit the Nextgen architecture and design guidelines perfectly.

If you are still looking for help with this component, I’d be happy to share my code or submit a Draft PR so you can take a look.

<img width="249" height="637" alt="Image" src="https://github.com/user-attachments/assets/fa04bea5-fe82-4817-8012-eaf08b86dc5d" />

**Comment by SenkJu** [comment]
Please do if you like!


> Hello everyone!
> 
> I just checked out the Nextgen UI roadmap and noticed that the HUD Editor is still on the to-do list. 
> 
> I actually have a semi-complete, fully modular HUD Editor that I built for my own project. It already manages essential elements. Right now, the UI is designed specifically for my custom client, but I can easily adapt the style and code to fit the Nextgen architecture and design guidelines perfectly.
> 
> If you are still looking for help with this component, I’d be happy to share my code or submit a Draft PR so you can take a look.
> 
> <img width="249" height="637" alt="Image" src="https://github.com/user-attachments/assets/fa04bea5-fe82-4817-8012-eaf08b86dc5d" />

**Comment by minecrrrr** [comment]
Great, I'll prepare the code and submit a Draft PR in the near future 👌
> Please do if you like!

**Comment by minecrrrr** [comment]
HUD Editor ready for review #8399

**Comment by minecrrrr** [comment]
What about this marketplace UI concept?
Date: DD/MM/YY
Time: 24-hour format (can easily change)

<img width="1182" height="785" alt="Image" src="https://github.com/user-attachments/assets/45f01ddf-891b-40ea-8e8a-7f3a23d72a22" />

**Comment by minecrrrr** [comment]
there is another option:

<img width="1148" height="713" alt="Image" src="https://github.com/user-attachments/assets/533f79cf-0f6c-46f6-af5d-444493e62175" />
